In [13]:
import algorithm as al
import numpy as np
import pandas as pd

In [14]:
# train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
train = pd.read_csv('../data/Algerian_forest_fires_dataset_UPDATE.csv', header=None)
train

0   1   2     3     4     5     6    7     8    9   10
0    29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5   0
1    29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4   0
2    26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1   0
3    25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0   0
4    27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5   0
..   ..  ..  ..   ...   ...   ...   ...  ...   ...  ...  ..
239  30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5   1
240  28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0   0
241  27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2   0
242  24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7   0
243  24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5   0

[244 rows x 11 columns]

In [15]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[29. , 57. , 18. , ...,  1.3,  3.4,  0.5],
       [29. , 61. , 13. , ...,  1. ,  3.9,  0.4],
       [26. , 82. , 22. , ...,  0.3,  2.7,  0.1],
       ...,
       [27. , 87. , 29. , ...,  0.4,  3.4,  0.2],
       [24. , 54. , 18. , ...,  1.7,  5.1,  0.7],
       [24. , 64. , 15. , ...,  1.2,  4.8,  0.5]])

In [16]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.01  0.011 0.014 ... 0.017 0.017 0.017]
 [0.01  0.011 0.014 ... 0.017 0.017 0.017]
 [0.006 0.006 0.008 ... 0.011 0.012 0.011]
 ...
 [0.007 0.007 0.009 ... 0.012 0.013 0.012]
 [0.01  0.009 0.013 ... 0.016 0.017 0.017]
 [0.009 0.01  0.013 ... 0.016 0.016 0.016]]

N =  [[0.737 0.735 0.704 ... 0.68  0.676 0.68 ]
 [0.737 0.733 0.705 ... 0.681 0.677 0.682]
 [0.789 0.789 0.761 ... 0.732 0.724 0.727]
 ...
 [0.781 0.779 0.75  ... 0.723 0.716 0.719]
 [0.747 0.748 0.716 ... 0.683 0.68  0.682]
 [0.748 0.743 0.714 ... 0.689 0.684 0.688]]

H =  [[0.252 0.254 0.282 ... 0.303 0.306 0.303]
 [0.253 0.256 0.281 ... 0.302 0.306 0.301]
 [0.205 0.205 0.231 ... 0.257 0.264 0.262]
 ...
 [0.212 0.214 0.241 ... 0.265 0.272 0.269]
 [0.244 0.242 0.272 ... 0.3   0.303 0.301]
 [0.243 0.247 0.273 ... 0.295 0.3   0.296]]


In [20]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

weights = {
    'distance_function': 1,
    'hamming_distance': 0.5,
    'euclidean_distance': 0.5,
    'normalized_euclidean_distance': 0.5,
    'hausdorff_distance': 0,
    'yang_chiclana_distance': 0,
    'wang_xin_distance': 0,
    'liu_jiang_distance': 0,
    'he_distance': 0,
    'thao_distance': 0,
    'mahanta_panda_distance': 0,
}

# Chuyển đổi dictionary trọng số thành mảng
weights_array = np.array(list(weights.values()))
# print(weights_array)
# Normalization để đảm bảo tổng trọng số bằng 1
weights_array /= np.sum(weights_array)
# print(weights_array)
# Vòng lặp qua các độ đo
# for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
U, S = al.method3_combined(R_train, 2, 1.7, 0.5, 1, weights_array)

# Gán nhãn dựa trên khoảng cách tới các tâm cụm
y = np.array([np.argmin([al.combined_distance(X[i], S[j], weights_array) for j in range(S.shape[0])]) for i in range(P)])

# Tính toán các chỉ số đánh giá
CA = round(al.calculate_CA(true_labels, y), 2)
PC = round(al.calculate_PC(U), 2)
SC = round(al.calculate_SC(X, U, S, 1.7), 2)
XB = round(al.calculate_XB(X, U, S), 2)
DI = round(al.calculate_DI(X, U), 2)

# In ra các chỉ số đánh giá cho mỗi độ đo
# print(f'Measure: {measure_name}')
print(f'  Clustering Accuracy (CA): {CA}')
print(f'  Partition Coefficient (PC): {PC}')
print(f'  Partition Index (SC): {SC}')
print(f'  Xie-Beni Index (XB): {XB}')
print(f'  Dunn Index (DI): {DI}')
print('------------------------------------------------')

  Clustering Accuracy (CA): 0.61
  Partition Coefficient (PC): 0.66
  Partition Index (SC): 4.61
  Xie-Beni Index (XB): 11.24
  Dunn Index (DI): 0.04
------------------------------------------------


In [37]:
M, N, H = al.method2_1(R_train, 0, 1, 0.5, 1)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

weights = {
    'distance_function': 1,
    'hamming_distance': 0.5,
    'euclidean_distance': 0.5,
    'normalized_euclidean_distance': 0.5,
    'hausdorff_distance': 0,
    'yang_chiclana_distance': 0,
    'wang_xin_distance': 0,
    'liu_jiang_distance': 0,
    'he_distance': 0,
    'thao_distance': 0,
    'mahanta_panda_distance': 0,
}

# Chuyển đổi dictionary trọng số thành mảng
weights_array = np.array(list(weights.values()))
# print(weights_array)
# Normalization để đảm bảo tổng trọng số bằng 1
weights_array /= np.sum(weights_array)

# Vòng lặp qua các độ đo
# for measure_name, measure_func in distance_measures.items():
# Phân cụm sử dụng độ đo hiện tại
U, S = al.method3_combined_method_2(R_train, 2, 1.7, 0.5, 1, weights_array)

# Gán nhãn dựa trên khoảng cách tới các tâm cụm
y = np.array([np.argmin([al.combined_distance(X[i], S[j], weights_array) for j in range(S.shape[0])]) for i in range(P)])

# Tính toán các chỉ số đánh giá
CA = round(al.calculate_CA(true_labels, y), 2)
PC = round(al.calculate_PC(U), 2)
SC = round(al.calculate_SC(X, U, S, 1.7), 2)
XB = round(al.calculate_XB(X, U, S), 2)
DI = round(al.calculate_DI(X, U), 2)

# In ra các chỉ số đánh giá cho mỗi độ đo
# print(f'Measure: {measure_name}')
print(f'  Clustering Accuracy (CA): {CA}')
print(f'  Partition Coefficient (PC): {PC}')
print(f'  Partition Index (SC): {SC}')
print(f'  Xie-Beni Index (XB): {XB}')
print(f'  Dunn Index (DI): {DI}')
print('------------------------------------------------')

  Clustering Accuracy (CA): 0.08
  Partition Coefficient (PC): 0.71
  Partition Index (SC): 0.31
  Xie-Beni Index (XB): 0.32
  Dunn Index (DI): 0.08
------------------------------------------------
