In [11]:
import algorithm as al
import numpy as np
import pandas as pd

In [12]:
# train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
train = pd.read_csv('../data/breast+cancer+wisconsin+diagnostic/wdbc.csv', header=None)
train

0      1      2       3       4        5        6        7   \
0      842302  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ...    ...    ...     ...     ...      ...      ...      ...   
564    926424  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          8       9   ...      21     22      23      24       25       26  \
0    0.14710  0.2419  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560   
1    0.07017  0.1812  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660   
2    0.12790  0.2069  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450   
3    0.10520  0.2597  ...  14.910  26.50   98.87   567.7  0.20980  0.86630   
4    0.10430  0.1809  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500   
..       ...     ...  ...     ...    ...     ...     ...      ...      ...   
564  0.13890  0.1726  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130   
565  0.09791  0.1752  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220   
566  0.05302  0.1590  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940   
567  0.15200  0.2397  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810   
568  0.00000  0.1587  ...   9.456  30.37   59.16   268.6  0.08996  0.06444   

         27      28      29  30  
0    0.7119  0.2654  0.4601   M  
1    0.2416  0.1860  0.2750   M  
2    0.4504  0.2430  0.3613   M  
3    0.6869  0.2575  0.6638   M  
4    0.4000  0.1625  0.2364   M  
..      ...     ...     ...  ..  
564  0.4107  0.2216  0.2060   M  
565  0.3215  0.1628  0.2572   M  
566  0.3403  0.1418  0.2218   M  
567  0.9387  0.2650  0.4087   M  
568  0.0000  0.0000  0.2871   B  

[569 rows x 31 columns]

In [13]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[842302, 17.99, 10.38, ..., 0.7119, 0.2654, 0.4601],
       [842517, 20.57, 17.77, ..., 0.2416, 0.186, 0.275],
       [84300903, 19.69, 21.25, ..., 0.4504, 0.243, 0.3613],
       ...,
       [926954, 16.6, 28.08, ..., 0.3403, 0.1418, 0.2218],
       [927241, 20.6, 29.33, ..., 0.9387, 0.265, 0.4087],
       [92751, 7.76, 24.54, ..., 0.0, 0.0, 0.2871]], dtype=object)

In [14]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.028 0.003 0.003 ... 0.005 0.003 0.004]
 [0.039 0.005 0.005 ... 0.008 0.004 0.006]
 [0.038 0.005 0.005 ... 0.008 0.004 0.006]
 ...
 [0.043 0.006 0.006 ... 0.008 0.005 0.007]
 [0.026 0.003 0.003 ... 0.005 0.003 0.004]
 [0.034 0.004 0.004 ... 0.005 0.003 0.005]]

N =  [[0.611 0.839 0.841 ... 0.8   0.846 0.823]
 [0.554 0.804 0.806 ... 0.77  0.818 0.79 ]
 [0.561 0.809 0.813 ... 0.766 0.818 0.794]
 ...
 [0.539 0.796 0.791 ... 0.759 0.81  0.777]
 [0.617 0.843 0.843 ... 0.804 0.85  0.828]
 [0.58  0.83  0.82  ... 0.803 0.844 0.806]]

H =  [[0.361 0.158 0.156 ... 0.195 0.151 0.173]
 [0.406 0.191 0.189 ... 0.223 0.178 0.204]
 [0.401 0.186 0.183 ... 0.226 0.177 0.2  ]
 ...
 [0.418 0.198 0.203 ... 0.232 0.185 0.216]
 [0.356 0.154 0.154 ... 0.191 0.147 0.168]
 [0.386 0.166 0.176 ... 0.192 0.153 0.189]]


In [15]:
# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    cluster_labels = {0: 'B', 1: 'M'}

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y_indices = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Ánh xạ chỉ số cụm với nhãn chuỗi
    y = np.array([cluster_labels[index] for index in y_indices])
    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    # y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.4
  Partition Coefficient (PC): 0.87
  Partition Index (SC): 0.13
  Xie-Beni Index (XB): 1.33
  Dunn Index (DI): 0.01
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.58
  Partition Coefficient (PC): 0.7
  Partition Index (SC): 0.28
  Xie-Beni Index (XB): 2.06
  Dunn Index (DI): 0.01
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.42
  Partition Coefficient (PC): 0.67
  Partition Index (SC): 0.33
  Xie-Beni Index (XB): 2.3
  Dunn Index (DI): 0.01
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.58
  Partition Coefficient (PC): 0.67
  Partition Index (SC): 0.33
  Xie-Beni Index (XB): 2.3
  Dunn Index (DI): 0.01
------------------------------------------------
Measure: hausdorff_distance
  Clustering Accuracy (CA): 0.49
  Partition Coefficient (PC): 0

In [16]:
M, N, H = al.method2_1(R_train, 0, 1, 0.45, 1)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3_1(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.72
  Partition Index (SC): 0.53
  Xie-Beni Index (XB): 0.42
  Dunn Index (DI): 0.08
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 266253369837253.7
  Xie-Beni Index (XB): 166678445059812.53
  Dunn Index (DI): 0.08
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 674609827806901.5
  Xie-Beni Index (XB): 422315470371897.2
  Dunn Index (DI): 0.07
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 23838035114044.34
  Xie-Beni Index (XB): 14922953382782.68
  Dunn Index (DI): 0.07
------------------------------------------------
Measure: hausdor

KeyboardInterrupt: 