In [1]:
import algorithm as al
import numpy as np
import pandas as pd

In [2]:
# train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
train = pd.read_csv('../data/haberman/haberman.data', header=None)
train

0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [3]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[30, 64,  1],
       [30, 62,  3],
       [30, 65,  0],
       [31, 59,  2],
       [31, 65,  4],
       [33, 58, 10],
       [33, 60,  0],
       [34, 59,  0],
       [34, 66,  9],
       [34, 58, 30],
       [34, 60,  1],
       [34, 61, 10],
       [34, 67,  7],
       [34, 60,  0],
       [35, 64, 13],
       [35, 63,  0],
       [36, 60,  1],
       [36, 69,  0],
       [37, 60,  0],
       [37, 63,  0],
       [37, 58,  0],
       [37, 59,  6],
       [37, 60, 15],
       [37, 63,  0],
       [38, 69, 21],
       [38, 59,  2],
       [38, 60,  0],
       [38, 60,  0],
       [38, 62,  3],
       [38, 64,  1],
       [38, 66,  0],
       [38, 66, 11],
       [38, 60,  1],
       [38, 67,  5],
       [39, 66,  0],
       [39, 63,  0],
       [39, 67,  0],
       [39, 58,  0],
       [39, 59,  2],
       [39, 63,  4],
       [40, 58,  2],
       [40, 58,  0],
       [40, 65,  0],
       [41, 60, 23],
       [41, 64,  0],
       [41, 67,  0],
       [41, 58,  0],
       [41, 5

In [4]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.012 0.014 0.067]
 [0.012 0.013 0.069]
 [0.012 0.014 0.064]
 [0.011 0.01  0.062]
 [0.012 0.015 0.068]
 [0.011 0.009 0.063]
 [0.012 0.011 0.065]
 [0.012 0.011 0.063]
 [0.012 0.016 0.072]
 [0.009 0.008 0.06 ]
 [0.013 0.012 0.068]
 [0.013 0.013 0.078]
 [0.012 0.015 0.066]
 [0.013 0.012 0.067]
 [0.013 0.015 0.083]
 [0.014 0.015 0.073]
 [0.013 0.012 0.07 ]
 [0.01  0.013 0.054]
 [0.014 0.012 0.07 ]
 [0.015 0.016 0.075]
 [0.012 0.01  0.061]
 [0.013 0.011 0.071]
 [0.013 0.011 0.08 ]
 [0.015 0.016 0.075]
 [0.01  0.012 0.06 ]
 [0.013 0.011 0.068]
 [0.014 0.012 0.071]
 [0.014 0.012 0.071]
 [0.015 0.015 0.08 ]
 [0.015 0.018 0.077]
 [0.014 0.018 0.069]
 [0.013 0.017 0.078]
 [0.014 0.012 0.072]
 [0.013 0.017 0.069]
 [0.014 0.018 0.07 ]
 [0.016 0.017 0.078]
 [0.013 0.017 0.065]
 [0.012 0.01  0.062]
 [0.013 0.011 0.069]
 [0.016 0.017 0.084]
 [0.012 0.01  0.064]
 [0.012 0.01  0.063]
 [0.015 0.019 0.075]
 [0.012 0.011 0.083]
 [0.016 0.019 0.079]
 [0.013 0.018 0.066]
 [0.012 0.01  0.063]
 [0.014 

In [5]:
# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.32
  Partition Coefficient (PC): 0.82
  Partition Index (SC): 0.19
  Xie-Beni Index (XB): 3.56
  Dunn Index (DI): 0.03
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.34
  Partition Coefficient (PC): 0.65
  Partition Index (SC): 0.35
  Xie-Beni Index (XB): 5.0
  Dunn Index (DI): 0.03
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.33
  Partition Coefficient (PC): 0.63
  Partition Index (SC): 0.38
  Xie-Beni Index (XB): 5.37
  Dunn Index (DI): 0.03
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.41
  Partition Coefficient (PC): 0.63
  Partition Index (SC): 0.38
  Xie-Beni Index (XB): 5.37
  Dunn Index (DI): 0.03
------------------------------------------------
Measure: hausdorff_distance
  Clustering Accuracy (CA): 0.34
  Partition Coefficient (PC)

In [6]:
M, N, H = al.method2_1(R_train, 0, 1, 0.45, 1)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3_1(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.43
  Partition Coefficient (PC): 0.7
  Partition Index (SC): 0.71
  Xie-Beni Index (XB): 0.98
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.27
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 1.5197030384006312e+16
  Xie-Beni Index (XB): 1.7567870728470006e+16
  Dunn Index (DI): 0.04
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.3
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 1483894960490127.8
  Xie-Beni Index (XB): 1715392690663707.5
  Dunn Index (DI): 0.03
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.43
  Partition Coefficient (PC): 0.5
  Partition Index (SC): 449329011202190.75
  Xie-Beni Index (XB): 519427400214906.6
  Dunn Index (DI): 0.03
------------------------------------------------
Me