In [19]:
import algorithm as al
import numpy as np
import pandas as pd

In [20]:
# train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
train = pd.read_csv('../data/iris/iris.data', header=None)
label_mapping = {'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 3}
train[4] = train[4].map(label_mapping)
train

0    1    2    3  4
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [21]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.017 0.024 0.015 0.015]
 [0.017 0.023 0.015 0.015]
 [0.016 0.022 0.014 0.014]
 [0.017 0.022 0.014 0.014]
 [0.017 0.023 0.014 0.014]
 [0.018 0.024 0.015 0.015]
 [0.017 0.023 0.014 0.014]
 [0.017 0.024 0.015 0.015]
 [0.016 0.02  0.014 0.014]
 [0.017 0.023 0.015 0.014]
 [0.017 0.024 0.015 0.015]
 [0.017 0.024 0.015 0.015]
 [0.016 0.022 0.014 0.014]
 [0.015 0.019 0.013 0.013]
 [0.016 0.021 0.014 0.014]
 [0.016 0.02  0.014 0.014]
 [0.017 0.023 0.015 0.015]
 [0.018 0.024 0.015 0.015]
 [0.018 0.024 0.015 0.015]
 [0.017 0.023 0.015 0.015]
 [0.018 0.025 0.016 0.016]
 [0.018 0.024 0.015 0.015]
 [0.015 0.021 0.013 0.013]
 [0.019 0.026 0.017 0.017]
 [0.017 0.024 0.015 0.015]
 [0.018 0.023 0.015 0.015]
 [0.018 0.025 0.016 0.016]
 [0.018 0.024 0.015 0.015]
 [0.017 0.024 0.015 0.015]
 [0.017 0.023 0.015 0.015]
 [0.017 0.023 0.015 0.015]
 [0.019 0.025 0.016 0.016]
 [0.016 0.02  0.013 0.013]
 [0.016 0.02  0.013 0.013]
 [0.017 0.023 0.015 0.014]
 [0.017 0.023 0.015 0.015]
 [0.017 0.024 0.015 0.0

In [23]:
# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3(R_train, len(np.unique(train[:, -1])), 1.7, 0.45,1, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.11
  Partition Coefficient (PC): 0.88
  Partition Index (SC): 0.01
  Xie-Beni Index (XB): 2.55
  Dunn Index (DI): 0.13
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.54
  Partition Coefficient (PC): 0.73
  Partition Index (SC): 0.02
  Xie-Beni Index (XB): 3.31
  Dunn Index (DI): 0.06
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.01
  Partition Coefficient (PC): 0.72
  Partition Index (SC): 0.02
  Xie-Beni Index (XB): 3.44
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.45
  Partition Coefficient (PC): 0.72
  Partition Index (SC): 0.02
  Xie-Beni Index (XB): 3.44
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: hausdorff_distance
  Clustering Accuracy (CA): 0.02
  Partition Coefficient (PC

In [24]:
M, N, H = al.method2_1(R_train, 0, 1, 0.45, 1)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3_1(R_train, len(np.unique(train[:, -1])), 1.7, 0.45,1, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.65
  Partition Coefficient (PC): 0.81
  Partition Index (SC): 0.04
  Xie-Beni Index (XB): 0.67
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.63
  Partition Coefficient (PC): 0.58
  Partition Index (SC): 0.07
  Xie-Beni Index (XB): 1.09
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.56
  Partition Index (SC): 0.08
  Xie-Beni Index (XB): 1.26
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 0.56
  Partition Index (SC): 0.08
  Xie-Beni Index (XB): 1.26
  Dunn Index (DI): 0.05
------------------------------------------------
Measure: hausdorff_distance
  Clustering Accuracy (CA): 0.0
  Partition Coefficient (PC): 