In [27]:
import algorithm as al
import numpy as np
import pandas as pd

In [28]:
train = pd.read_excel('test.xlsx')
train

a  b   c   d   e class
0  6  4   1  10   9     a
1  7  2   4   6   8     a
2  6  7  10   9   2     a
3  7  3   8   1   4     a
4  7  4   8   5  10     a

In [29]:
train = train.to_numpy()
R_train = train[:, 0:5]
R_train

array([[6, 4, 1, 10, 9],
       [7, 2, 4, 6, 8],
       [6, 7, 10, 9, 2],
       [7, 3, 8, 1, 4],
       [7, 4, 8, 5, 10]], dtype=object)

In [30]:
Nd = al.normalization(R_train, 0, 1)
Nd

array([[0.        , 0.4       , 0.        , 1.        , 0.875     ],
       [1.        , 0.        , 0.33333333, 0.55555556, 0.75      ],
       [0.        , 1.        , 1.        , 0.88888889, 0.        ],
       [1.        , 0.2       , 0.77777778, 0.        , 0.25      ],
       [1.        , 0.4       , 0.77777778, 0.44444444, 1.        ]])

In [31]:
dis = al.distance(Nd)
dis

array([[0.        , 1.21830496, 1.46218011, 1.74228679, 1.38895833],
       [1.21830496, 0.        , 1.76580168, 0.89228518, 0.65755345],
       [1.46218011, 1.76580168, 0.        , 1.59436701, 1.61459394],
       [1.74228679, 0.89228518, 1.59436701, 0.        , 0.89444444],
       [1.38895833, 0.65755345, 1.61459394, 0.89444444, 0.        ]])

In [32]:
prod = al.product(dis,Nd)
prod

array([[4.34955009, 2.3662208 , 4.30369464, 2.59386656, 2.73825875],
       [1.54983863, 2.69460208, 2.97123172, 3.08015243, 1.94664159],
       [4.97476262, 1.54958302, 3.08445907, 3.16077835, 4.61694454],
       [1.78672962, 2.64905951, 2.58747442, 4.05274677, 3.08815927],
       [1.5519979 , 2.34906616, 2.52945743, 3.18946042, 1.93211474]])

In [33]:
M = al.membershipValue(prod)
M

array([[0.22990884, 0.42261483, 0.23235849, 0.38552484, 0.36519558],
       [0.64522846, 0.37111231, 0.33656076, 0.32465926, 0.51370525],
       [0.20101462, 0.6453349 , 0.32420595, 0.31637777, 0.21659346],
       [0.55968177, 0.37749246, 0.38647725, 0.24674623, 0.3238175 ],
       [0.64433077, 0.42570108, 0.3953417 , 0.31353266, 0.51756761]])

In [34]:
N = al.nonMembershipValue(M, 0.45)
N

array([[0.19931366, 0.0802156 , 0.19706267, 0.09626429, 0.10614839],
       [0.02184684, 0.10318593, 0.12156082, 0.12853254, 0.04968234],
       [0.22807723, 0.02183031, 0.12880511, 0.13359653, 0.21204182],
       [0.03810669, 0.1000713 , 0.09582114, 0.18437086, 0.12903911],
       [0.0219866 , 0.07898592, 0.09177817, 0.13537824, 0.04862209]])

In [35]:
H = al.hesitancyValue(N, 0.45)
H

array([[0.5707775 , 0.49716957, 0.57057883, 0.51821087, 0.52865602],
       [0.33292469, 0.52570176, 0.54187842, 0.54680821, 0.43661241],
       [0.57090816, 0.33283479, 0.54698894, 0.5500257 , 0.57136472],
       [0.40221154, 0.52243624, 0.51770161, 0.5688829 , 0.5471434 ],
       [0.33368263, 0.495313  , 0.51288013, 0.55108911, 0.4338103 ]])

In [41]:
M, N, H = al.method1(R_train, 0, 1, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.23  0.423 0.232 0.386 0.365]
 [0.645 0.371 0.337 0.325 0.514]
 [0.201 0.645 0.324 0.316 0.217]
 [0.56  0.377 0.386 0.247 0.324]
 [0.644 0.426 0.395 0.314 0.518]]

N =  [[0.199 0.08  0.197 0.096 0.106]
 [0.022 0.103 0.122 0.129 0.05 ]
 [0.228 0.022 0.129 0.134 0.212]
 [0.038 0.1   0.096 0.184 0.129]
 [0.022 0.079 0.092 0.135 0.049]]

H =  [[0.571 0.497 0.571 0.518 0.529]
 [0.333 0.526 0.542 0.547 0.437]
 [0.571 0.333 0.547 0.55  0.571]
 [0.402 0.522 0.518 0.569 0.547]
 [0.334 0.495 0.513 0.551 0.434]]


In [42]:
M2 = al.normalization(M+R_train, 0, 1)
M2

array([[0.0200831 , 0.3890785 , 0.        , 1.        , 0.86110107],
       [1.        , 0.        , 0.34150902, 0.55564066, 0.7585833 ],
       [0.        , 1.        , 1.        , 0.88291936, 0.        ],
       [0.94113573, 0.19074706, 0.78684558, 0.        , 0.25382484],
       [0.99930748, 0.38964733, 0.78783546, 0.44501587, 1.        ]])

In [43]:
M2, N2, H2 = al.method2(R_train, 0, 1, 0.45, 1)

M2 = np.around(M2, 3)
N2 = np.around(N2, 3)
H2 = np.around(H2, 3)

print ("M' = \n",M2)
print ("\nN' = \n",N2)
print ("\nH' = \n",H2)


M' = 
 [[0.02  0.389 0.    1.    0.861]
 [1.    0.    0.341 0.556 0.759]
 [0.    1.    1.    0.883 0.   ]
 [0.941 0.191 0.787 0.    0.254]
 [0.999 0.39  0.788 0.445 1.   ]]

N' = 
 [[0.657 0.095 1.    0.    0.002]
 [0.    1.    0.119 0.039 0.008]
 [1.    0.    0.    0.002 1.   ]
 [0.    0.239 0.006 1.    0.178]
 [0.    0.094 0.006 0.072 0.   ]]

H' = 
 [[0.323 0.516 0.    0.    0.137]
 [0.    0.    0.54  0.405 0.233]
 [0.    0.    0.    0.115 0.   ]
 [0.059 0.57  0.207 0.    0.568]
 [0.001 0.516 0.206 0.483 0.   ]]
