In [1]:
import algorithm as al
import numpy as np
import pandas as pd

In [2]:
train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
# train = pd.read_csv('../../../GR1/occupancy_train.csv')
train

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0    87524       442.246011       253.291155      0.819738       90546   
1    75166       406.690687       243.032436      0.801805       78789   
2    90856       442.267048       266.328318      0.798354       93717   
3    45928       286.540559       208.760042      0.684989       47336   
4    79408       352.190770       290.827533      0.564011       81463   
..     ...              ...              ...           ...         ...   
895  83248       430.077308       247.838695      0.817263       85839   
896  87350       440.735698       259.293149      0.808629       90899   
897  99657       431.706981       298.837323      0.721684      106264   
898  93523       476.344094       254.176054      0.845739       97653   
899  85609       512.081774       215.271976      0.907345       89197   

       Extent  Perimeter    Class  
0    0.758651   1184.040  Kecimen  
1    0.684130   1121.786  Kecimen  
2    0.637613   1208.575  Kecimen  
3    0.699599    844.162  Kecimen  
4    0.792772   1073.251  Kecimen  
..        ...        ...      ...  
895  0.668793   1129.072    Besni  
896  0.636476   1214.252    Besni  
897  0.741099   1292.828    Besni  
898  0.658798   1258.548    Besni  
899  0.632020   1272.862    Besni  

[900 rows x 8 columns]

In [3]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[87524, 442.2460114, 253.291155, ..., 90546, 0.758650579, 1184.04],
       [75166, 406.690687, 243.0324363, ..., 78789, 0.68412957, 1121.786],
       [90856, 442.2670483, 266.3283177, ..., 93717, 0.637612812,
        1208.575],
       ...,
       [99657, 431.7069809, 298.8373229, ..., 106264, 0.741098519,
        1292.828],
       [93523, 476.3440939, 254.1760536, ..., 97653, 0.658798253,
        1258.548],
       [85609, 512.0817743, 215.2719758, ..., 89197, 0.632019963,
        1272.862]], dtype=object)

In [4]:
Nd = al.normalization(R_train, 0, 1)
Nd

array([[0.29637031, 0.28071404, 0.314376  , ..., 0.25550425, 0.83142179,
        0.27179088],
       [0.23742726, 0.23463777, 0.28494465, ..., 0.20886392, 0.66785449,
        0.24184205],
       [0.31226271, 0.2807413 , 0.35177845, ..., 0.26808369, 0.56575414,
        0.28359405],
       ...,
       [0.3542402 , 0.26705647, 0.44504387, ..., 0.31785796, 0.79289651,
        0.32412604],
       [0.32498331, 0.32490187, 0.31691469, ..., 0.2836979 , 0.61225439,
        0.3076348 ],
       [0.28723648, 0.37121445, 0.20530238, ..., 0.25015273, 0.55347831,
        0.3145209 ]])

In [5]:
dis = al.distance(Nd)
dis

array([[0.        , 0.19272977, 0.2715581 , ..., 0.2329686 , 0.23385554,
        0.34594269],
       [0.19272977, 0.        , 0.16702991, ..., 0.3027792 , 0.18704494,
        0.27775937],
       [0.2715581 , 0.16702991, 0.        , ..., 0.28632996, 0.11081103,
        0.25153131],
       ...,
       [0.2329686 , 0.3027792 , 0.28632996, ..., 0.        , 0.30917888,
        0.47584228],
       [0.23385554, 0.18704494, 0.11081103, ..., 0.30917888, 0.        ,
        0.17533308],
       [0.34594269, 0.27775937, 0.25153131, ..., 0.47584228, 0.17533308,
        0.        ]])

In [6]:
prod = al.product(dis,Nd)
prod

array([[114.64105104,  98.9334177 , 115.33782712, ..., 100.0159031 ,
        229.60469887,  97.4785346 ],
       [117.3945365 ,  99.51249326, 114.65929314, ..., 102.23895446,
        213.74749419,  97.3258705 ],
       [112.90642441,  96.86912719, 115.12373525, ...,  98.2934812 ,
        240.17422306,  95.66653574],
       ...,
       [114.65612228, 102.86909221, 116.07761573, ..., 100.129868  ,
        254.31526815, 100.45741863],
       [109.59894162,  93.20533339, 114.59228313, ...,  95.40935559,
        242.3906545 ,  93.10463619],
       [133.67739146, 112.62818934, 141.44413408, ..., 116.09885362,
        293.5424756 , 113.06174868]])

In [7]:
M = al.membershipValue(prod)
M

array([[0.00872288, 0.01010781, 0.00867018, ..., 0.00999841, 0.00435531,
        0.01025867],
       [0.00851828, 0.01004899, 0.00872149, ..., 0.00978101, 0.00467842,
        0.01027476],
       [0.00885689, 0.01032321, 0.00868631, ..., 0.01017361, 0.00416364,
        0.01045298],
       ...,
       [0.00872173, 0.00972109, 0.00861493, ..., 0.00998703, 0.00393213,
        0.00995447],
       [0.00912418, 0.010729  , 0.00872659, ..., 0.01048115, 0.00412557,
        0.0107406 ],
       [0.0074807 , 0.00887877, 0.00706993, ..., 0.00861335, 0.00340666,
        0.00884472]])

In [8]:
N = al.nonMembershipValue(M, 0.45)
N

array([[0.7557839 , 0.74040865, 0.75639817, ..., 0.74157316, 0.81765751,
        0.73881573],
       [0.75818194, 0.74103377, 0.75580005, ..., 0.74391136, 0.81202951,
        0.73864669],
       [0.75423211, 0.73813879, 0.75620998, ..., 0.73971198, 0.82111572,
        0.73678567],
       ...,
       [0.75579724, 0.74456149, 0.75704479, ..., 0.74169476, 0.82542302,
        0.74204318],
       [0.75118037, 0.7339424 , 0.75574072, ..., 0.73649327, 0.82181399,
        0.73382389],
       [0.7709308 , 0.75398015, 0.77628028, ..., 0.75706327, 0.83579831,
        0.7543724 ]])

In [9]:
H = al.hesitancyValue(N, 0.45)
H

array([[0.23549322, 0.24948354, 0.23493165, ..., 0.24842843, 0.17798718,
        0.2509256 ],
       [0.23329978, 0.24891724, 0.23547846, ..., 0.24630763, 0.18329207,
        0.25107855],
       [0.236911  , 0.251538  , 0.23510372, ..., 0.25011441, 0.17472063,
        0.25276136],
       ...,
       [0.23548102, 0.24571742, 0.23434028, ..., 0.24831821, 0.17064485,
        0.24800235],
       [0.23969546, 0.2553286 , 0.23553269, ..., 0.25302558, 0.17406044,
        0.25543551],
       [0.22158851, 0.23714108, 0.21664979, ..., 0.23432338, 0.16079502,
        0.23678288]])

In [10]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.009 0.01  0.009 ... 0.01  0.004 0.01 ]
 [0.009 0.01  0.009 ... 0.01  0.005 0.01 ]
 [0.009 0.01  0.009 ... 0.01  0.004 0.01 ]
 ...
 [0.009 0.01  0.009 ... 0.01  0.004 0.01 ]
 [0.009 0.011 0.009 ... 0.01  0.004 0.011]
 [0.007 0.009 0.007 ... 0.009 0.003 0.009]]

N =  [[0.756 0.74  0.756 ... 0.742 0.818 0.739]
 [0.758 0.741 0.756 ... 0.744 0.812 0.739]
 [0.754 0.738 0.756 ... 0.74  0.821 0.737]
 ...
 [0.756 0.745 0.757 ... 0.742 0.825 0.742]
 [0.751 0.734 0.756 ... 0.736 0.822 0.734]
 [0.771 0.754 0.776 ... 0.757 0.836 0.754]]

H =  [[0.235 0.249 0.235 ... 0.248 0.178 0.251]
 [0.233 0.249 0.235 ... 0.246 0.183 0.251]
 [0.237 0.252 0.235 ... 0.25  0.175 0.253]
 ...
 [0.235 0.246 0.234 ... 0.248 0.171 0.248]
 [0.24  0.255 0.236 ... 0.253 0.174 0.255]
 [0.222 0.237 0.217 ... 0.234 0.161 0.237]]


In [11]:
U, S = al.method3(R_train, 2, 1.7, 0.45)

Initial centroids:
[[[3.27284152e-01 1.26964495e-01 5.45751353e-01]
  [9.21733093e-01 6.19531137e-04 7.76473759e-02]
  [1.39311367e-01 3.07373151e-01 5.53315482e-01]
  [7.09816744e-01 1.32587599e-02 2.76924496e-01]
  [6.51729183e-02 4.63309233e-01 4.71517848e-01]
  [4.75961508e-01 6.09794902e-02 4.63059002e-01]
  [8.68498450e-01 2.03334612e-03 1.29468204e-01]]

 [[8.03540225e-01 5.19248788e-03 1.91267287e-01]
  [9.39157325e-01 3.50054236e-04 6.04926203e-02]
  [4.14150429e-01 8.36681306e-02 5.02181441e-01]
  [8.08102116e-02 4.21136194e-01 4.98053595e-01]
  [8.82982533e-02 4.03236839e-01 5.08464907e-01]
  [5.06500541e-01 5.17058689e-02 4.41793591e-01]
  [2.75381593e-01 1.61542539e-01 5.63075869e-01]]]
iteration: 0
U:
[[0.46218407 0.53781593]
 [0.4622351  0.5377649 ]
 [0.46210951 0.53789049]
 ...
 [0.46227809 0.53772191]
 [0.46195142 0.53804858]
 [0.4636982  0.5363018 ]]
S:
[[[0.00723745 0.77533038 0.21743217]
  [0.00831537 0.76200248 0.22968215]
  [0.00712538 0.77680613 0.21606849]
  [0.