In [1]:
import algorithm as al
import numpy as np
import pandas as pd

In [2]:
# train = pd.read_excel('../archive/Raisin_Dataset.xlsx')
train = pd.read_csv('../data/wine/wine.csv', header=None)
train

0     1     2     3    4     5     6     7     8      9     10    11  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...   
173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

     12  
0     1  
1     1  
2     1  
3     1  
4     1  
..   ..  
173   3  
174   3  
175   3  
176   3  
177   3  

[178 rows x 13 columns]

In [3]:
train = train.to_numpy()
R_train = train[:, 0:-1]
R_train
# R_train = np.random.rand(100, 10)

array([[14.23,  1.71,  2.43, ...,  5.64,  1.04,  3.92],
       [13.2 ,  1.78,  2.14, ...,  4.38,  1.05,  3.4 ],
       [13.16,  2.36,  2.67, ...,  5.68,  1.03,  3.17],
       ...,
       [13.27,  4.28,  2.26, ..., 10.2 ,  0.59,  1.56],
       [13.17,  2.59,  2.37, ...,  9.3 ,  0.6 ,  1.62],
       [14.13,  4.1 ,  2.74, ...,  9.2 ,  0.61,  1.6 ]])

In [4]:
M, N, H = al.method1(R_train, 0.45)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

print ("M = ",M)
print ("\nN = ",N)
print ("\nH = ",H)

M =  [[0.012 0.016 0.011 ... 0.017 0.016 0.014]
 [0.013 0.018 0.012 ... 0.018 0.018 0.015]
 [0.013 0.019 0.012 ... 0.019 0.019 0.016]
 ...
 [0.01  0.019 0.01  ... 0.018 0.012 0.009]
 [0.011 0.019 0.01  ... 0.019 0.013 0.01 ]
 [0.01  0.018 0.009 ... 0.017 0.012 0.009]]

N =  [[0.724 0.686 0.736 ... 0.679 0.687 0.706]
 [0.716 0.673 0.726 ... 0.669 0.671 0.695]
 [0.711 0.665 0.718 ... 0.661 0.668 0.69 ]
 ...
 [0.74  0.666 0.745 ... 0.672 0.721 0.749]
 [0.734 0.663 0.738 ... 0.664 0.712 0.742]
 [0.743 0.671 0.747 ... 0.677 0.724 0.752]]

H =  [[0.264 0.298 0.254 ... 0.304 0.297 0.28 ]
 [0.272 0.309 0.263 ... 0.312 0.311 0.29 ]
 [0.276 0.316 0.269 ... 0.319 0.314 0.295]
 ...
 [0.25  0.315 0.245 ... 0.31  0.267 0.242]
 [0.255 0.318 0.252 ... 0.317 0.275 0.248]
 [0.247 0.311 0.243 ... 0.306 0.264 0.239]]


In [5]:
# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.18
  Partition Coefficient (PC): 0.78
  Partition Index (SC): 0.05
  Xie-Beni Index (XB): 3.92
  Dunn Index (DI): 0.08
------------------------------------------------
Measure: hamming_distance
  Clustering Accuracy (CA): 0.33
  Partition Coefficient (PC): 0.56
  Partition Index (SC): 0.08
  Xie-Beni Index (XB): 3.93
  Dunn Index (DI): 0.07
------------------------------------------------
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.2
  Partition Coefficient (PC): 0.54
  Partition Index (SC): 0.09
  Xie-Beni Index (XB): 4.07
  Dunn Index (DI): 0.08
------------------------------------------------
Measure: normalized_euclidean_distance
  Clustering Accuracy (CA): 0.44
  Partition Coefficient (PC): 0.54
  Partition Index (SC): 0.09
  Xie-Beni Index (XB): 4.07
  Dunn Index (DI): 0.04
------------------------------------------------
Measure: hausdorff_distance
  Clustering Accuracy (CA): 0.34
  Partition Coefficient (PC)

In [6]:
M, N, H = al.method2_1(R_train, 0, 1, 0.45, 1)

M = np.around(M, 3)
N = np.around(N, 3)
H = np.around(H, 3)

# Chuẩn bị dữ liệu cho phân cụm
X = np.dstack((M, N, H))
P = X.shape[0]
true_labels = train[:, -1]

# Danh sách các hàm độ đo khoảng cách
distance_measures = {
    'distance_function': al.distance_function,
    'hamming_distance': al.hamming_distance,
    'euclidean_distance': al.euclidean_distance,
    'normalized_euclidean_distance': al.normalized_euclidean_distance,
    'hausdorff_distance': al.hausdorff_distance,
    'yang_chiclana_distance': al.yang_chiclana_distance,
    'wang_xin_distance': al.wang_xin_distance,
    'liu_jiang_distance': al.liu_jiang_distance,
    'he_distance': al.he_distance,
    'thao_distance': al.thao_distance,
    'mahanta_panda_distance': al.mahanta_panda_distance,
}

# Vòng lặp qua các độ đo
for measure_name, measure_func in distance_measures.items():
    # Phân cụm sử dụng độ đo hiện tại
    U, S = al.method3_1(R_train, len(np.unique(train[:, -1])), 1.7, 0.45, measure_name)

    # Gán nhãn dựa trên khoảng cách tới các tâm cụm
    y = np.array([np.argmin([measure_func(X[i], S[j]) for j in range(S.shape[0])]) for i in range(P)])

    # Tính toán các chỉ số đánh giá
    CA = round(al.calculate_CA(true_labels, y), 2)
    PC = round(al.calculate_PC(U), 2)
    SC = round(al.calculate_SC(X, U, S, 1.7), 2)
    XB = round(al.calculate_XB(X, U, S), 2)
    DI = round(al.calculate_DI(X, U), 2)

    # In ra các chỉ số đánh giá cho mỗi độ đo
    print(f'Measure: {measure_name}')
    print(f'  Clustering Accuracy (CA): {CA}')
    print(f'  Partition Coefficient (PC): {PC}')
    print(f'  Partition Index (SC): {SC}')
    print(f'  Xie-Beni Index (XB): {XB}')
    print(f'  Dunn Index (DI): {DI}')
    print('------------------------------------------------')

Measure: distance_function
  Clustering Accuracy (CA): 0.65
  Partition Coefficient (PC): 0.58
  Partition Index (SC): 0.2
  Xie-Beni Index (XB): 0.89
  Dunn Index (DI): 0.24
------------------------------------------------
Error calculating DI: zero-size array to reduction operation maximum which has no identity
Measure: hamming_distance
  Clustering Accuracy (CA): 0.24
  Partition Coefficient (PC): 0.33
  Partition Index (SC): 8634363985636788.0
  Xie-Beni Index (XB): 4.123323296063627e+16
  Dunn Index (DI): 0
------------------------------------------------
Error calculating DI: zero-size array to reduction operation maximum which has no identity
Measure: euclidean_distance
  Clustering Accuracy (CA): 0.24
  Partition Coefficient (PC): 0.33
  Partition Index (SC): 6585804863275277.0
  Xie-Beni Index (XB): 9.407360305091408e+16
  Dunn Index (DI): 0
------------------------------------------------
Error calculating DI: zero-size array to reduction operation maximum which has no identi